// Form action types
export const FORM_ACTION_PENDING = 'FORM_ACTION_PENDING';
export const FORM_ACTION_FULFILLED = 'FORM_ACTION_FULFILLED';
export const FORM_ACTION_REJECTED = 'FORM_ACTION_REJECTED';
export const FORM_ACTION_FETCH_SCHEMA = 'FORM_ACTION_FETCH_SCHEMA';
export const FORM_ACTION_UPDATE_SCHEMA = 'FORM_ACTION_UPDATE_SCHEMA';